---
- name: "Download Vector packages"
  become: true
  ansible.builtin.get_url:
    url: "{{ vector_repo }}/{{ vector_version }}/vector-1.x86_64.rpm"
    dest: "/tmp/vector-{{ vector_version }}.x86_64.rpm"
    mode: "0755"
    timeout: 200
- name: "Install Vector packages"
  become: true
  ansible.builtin.yum:
    name: "/tmp/vector-{{ vector_version }}.x86_64.rpm"
    state: present
    disable_gpg_check: true
- name: "Create parent directory for Vector config"
  become: true
  ansible.builtin.file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: "0755"
- name: "Apply Vector template"
  become: true
  ansible.builtin.template:
    src: "vector.yml.j2"
    dest: "{{ vector_config_dir }}/vector.yml"
    mode: "0644"
- name: "Change Vector systemd unit"
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /usr/lib/systemd/system/vector.service
    mode: "0644"
    backup: true
  notify: "Start Vector service"
