---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: podman-cl8
    image: docker.io/geerlingguy/docker-centos8-ansible
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    systemd: true 
    command: /sbin/init  
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 1    
    ANSIBLE_LOCAL_TEMP: "${WORKSPACE:-$HOME}/.ansible/tmp"
    ANSIBLE_REMOTE_TMP: "/tmp"
  playbooks:
    verify: ../shared/tests/verify.yml
verifier:
  name: ansible
    #scenario:
    #  test_sequence:
    #    - destroy
    #    - create
    #    - converge
    #    - destroy  
