---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8
    image: geerlingguy/docker-centos8-ansible 
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 1
    ANSIBLE_LOCAL_TEMP: "${WORKSPACE:-$HOME}/.ansible/tmp"
    ANSIBLE_REMOTE_TMP: "/tmp"      
    playbooks:
    verify: ../shared/tests/verify.yml
verifier:
  name: ansible

